name: Convert Unix Timestamp

on:
  workflow_dispatch:
    inputs:
      timestamp:
        description: 'Unix Timestamp'
        required: true

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Convert timestamp
        run: python convert.py ${{ github.event.inputs.timestamp }}
